import { demoApi as api, resetDemo } from './demo-adapter.js';
import {translator,messages} from './i18n.js';
let S,token,page=new URLSearchParams(location.search).has('oauth')?'settings':(['today','contracts','settings','inbox','projects','logs'].includes(new URLSearchParams(location.search).get('page'))?new URLSearchParams(location.search).get('page'):'today'),range=0,dirty=false,oauthBusy=false,savingCount=0,t=translator();
const saveFeedback=new Map();
const $=id=>document.getElementById(id),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const locale=()=>S?.settings.locale||'en-US',localized=(o,k)=>o.translations?.[locale()]?.[k]??o[k];
const stamp=x=>x?new Date(x).toLocaleString(locale(),{timeZone:S.settings.timezone,month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):t('never');
const day=(x=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:S.settings.timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(x);
const shift=(d,n)=>{const x=new Date(d+'T12:00:00Z');x.setUTCDate(x.getUTCDate()+n);return x.toISOString().slice(0,10);};
const start=e=>e.start?.dateTime||e.start?.date,end=e=>e.end?.dateTime||e.end?.date,dateOf=e=>e.start?.date||day(new Date(start(e)));
const time=x=>!x?t('unknown'):x.length===10?t('allDay'):new Date(x).toLocaleTimeString(locale(),{timeZone:S.settings.timezone,hour:'2-digit',minute:'2-digit'});
const privateText=x=>S.settings.privacy?esc(t('hidden')):esc(x),category=x=>t('category.'+({'学校/孩子':'school','家庭':'family','个人预约':'personal','工作':'work'}[x]||'family'));
const tag=(text,type='')=>`<span class="tag ${type}">${esc(text)}</span>`,state=x=>t('state.'+x);
const link=(url,label=t('source'))=>!S.settings.privacy&&/^https:\/\/(mail\.google\.com|www\.google\.com|calendar\.google\.com)\//.test(url||'')?`<a target="_blank" rel="noopener noreferrer" href="${esc(url)}">${esc(label)} ↗</a>`:'';
function flash(text){$('notice').innerHTML=`<div class="banner">${esc(text)}</div>`;$('notice').scrollIntoView({block:'nearest'});}
async function act(path,b){try{const r=await api(path,b);dirty=false;await load();return r;}catch(e){flash(messages[e.message]?t(e.message):t('operationFailed')+' '+e.message);}}

function saveStatus(id){const f=saveFeedback.get(id);return f?t(f.key,f.values):'';}
async function saveSettingsAction(id,body,key,values={}){
 const button=$(id);if(button?.disabled)return;const previous=button?.textContent;
 savingCount++;if(button){button.disabled=true;button.textContent=t('saving');}
 saveFeedback.set(id,{key:'saving'});const pending=$(id+'Status');if(pending)pending.textContent=t('saving');
 try{await api('/api/settings',body);dirty=false;saveFeedback.set(id,{key,values});const done=$(id+'Status');if(done)done.textContent=t(key,values);await load();return true;}
 catch(e){saveFeedback.set(id,{key:'saveFailed'});const failed=$(id+'Status');if(failed)failed.textContent=t('saveFailed');flash(t('saveFailed')+' '+(messages[e.message]?t(e.message):e.message));return false;}
 finally{savingCount--;const current=$(id);if(current){current.disabled=false;current.textContent=previous;}}
}
async function load(){try{S=await api('/api/state');t=translator(locale());render();}catch{flash(t('serviceError'));}}
function activeEvents(){return S.events.filter(e=>e.status!=='cancelled'&&!e.attendees?.some(a=>a.self&&a.responseStatus==='declined')&&e.response!=='declined'&&(!S.settings.selectedCalendars.length||S.settings.selectedCalendars.includes(e.calendarId))).sort((a,b)=>start(a).localeCompare(start(b)));}
function todoItems(){return S.candidates.filter(c=>c.kind==='todo'&&!c.user.dismissed&&(!c.bill||(!c.bill.paid&&S.contracts.some(s=>s.latestBill?.id===c.id)))&&(!c.user.snooze||c.user.snooze<=day())&&(!c.due||c.due<=shift(day(),7))).sort((a,b)=>(a.due||'9999').localeCompare(b.due||'9999'));}
function reviews(){return S.candidates.filter(c=>!c.user.dismissed&&c.kind!=='todo'&&!['synced','existing','cancelled'].includes(c.result.status));}
function render(){document.documentElement.lang=locale();$('sidebar').innerHTML=`<a class="brand" href="./"><span class="logo">D</span> Daily Hub</a><div class="workspace">${t('workspace')} <span>DEMO</span></div><nav>${[['today','◷'],['inbox','▤'],['contracts','◈'],['projects','▦'],['settings','⚙'],['logs','≡']].map(([key,icon])=>`<button data-go="${key}" class="${page===key?'active':''}">${icon} <span>${t(key)}</span>${key==='inbox'?`<b>${reviews().length||''}</b>`:''}</button>`).join('')}</nav><div class="aside-bottom"><div class="local-dot">Browser-only sample</div><p>${t('motto')}</p><button id="quit" class="text-button">Reset sample</button></div>`;
 $('date').textContent=new Date().toLocaleDateString(locale(),{timeZone:S.settings.timezone,year:'numeric',month:'long',day:'numeric',weekday:'long'})+' · '+S.settings.timezone;$('eyebrow').textContent=t('eyebrow');$('heading').textContent=t('heading.'+page);$('privacy').textContent='◉ '+t(S.settings.privacy?'privacyOn':'privacy');$('sync').disabled=S.syncing;$('sync').textContent='Demo data';$('footerStatus').textContent=`${t('snapshot')} ${stamp(S.bridge?.generatedAt)} · ${'Synthetic data · No account connected'}`;
 $('content').innerHTML=({today:todayView,inbox:inboxView,contracts:contractsView,projects:projectPage,settings:settingsView,logs:logsView})[page]();bind();}
function todayView(){const today=day(),events=activeEvents(),next=events.find(e=>e.start?.dateTime&&new Date(start(e))>new Date()),todos=todoItems(),from=shift(today,range===1?1:0),to=shift(from,range===7?7:1),shown=events.filter(e=>dateOf(e)<to&&(e.end?.date?e.end.date>from:day(new Date(end(e)))>=from)),all=shown.filter(e=>e.start?.date),timed=shown.filter(e=>e.start?.dateTime),prior=[];
 for(const c of S.contracts.filter(c=>c.actionable&&c.days<=7).slice(0,2))prior.push({title:c.title,reason:t('contractReason',{date:c.anchor.date,kind:t('contract.'+c.anchor.kind)})});
 for(const c of todos.filter(c=>!c.user.done&&(c.due||'9999')<=shift(today,1)).slice(0,2))prior.push({title:localized(c,'title'),reason:t(c.bill?.autoPay?'bill.verify':c.due<today?'overdueReason':'dueReason',{date:c.due})});
 for(const e of events.filter(e=>e.start?.dateTime&&dateOf(e)===today&&new Date(start(e))>new Date()))if(prior.length<3)prior.push({title:e.summary,reason:t('eventReason',{time:time(start(e))})});
 for(const p of S.projects)if(prior.length<3&&localized(p,'next')?.length)prior.push({title:localized(p,'next')[0],reason:t('projectReason',{name:p.name})});
 const remaining=next?Math.ceil((new Date(start(next))-new Date())/60000):0;
 return `${!S.connected?`<div class="banner">${'Sample view only. Live integrations are intentionally unavailable in this public demo.'}</div>`:''}${S.statuses.some(s=>s.source==='gmail-export'&&s.state==='partial')?`<p class="muted">${t('partialMail')}</p>`:''}<div class="hero-grid"><section class="next"><div class="eyebrow">${t('upNext')}</div><span class="clock">${next?t(remaining<60?'minutesAway':'hoursAway',{n:remaining,h:Math.floor(remaining/60),m:remaining%60}):'—'}</span><h2>${next?privateText(next.summary):t('noUpcoming')}</h2><p>${next?`${dateOf(next)} · ${time(start(next))} — ${time(end(next))}`:t('checkCoverage')}</p><div class="muted">${next?privateText(next.location||t('noLocation')):''}</div></section><section class="card priorities"><h2>${t('priorities')}</h2>${prior.slice(0,3).map((p,i)=>`<div class="priority"><span class="rank">${i+1}</span><div><strong>${privateText(p.title)}</strong><p>${privateText(p.reason)}</p></div></div>`).join('')||`<div class="empty">${t('noPriorities')}</div>`}</section></div>
 <div class="columns"><section class="card"><div class="section-head"><h2>${t('timeline')} <span class="muted">${shown.length}</span></h2><div class="tabs">${[[0,'today'],[1,'tomorrow'],[7,'week']].map(([i,key])=>`<button data-range="${i}" class="${range===i?'active':''}">${t(key)}</button>`).join('')}</div></div>${all.map(e=>`<div class="all-day">${tag(t('allDay'))}${range===7?dateOf(e)+' · ':''}${privateText(e.summary)}</div>`).join('')}<div class="timeline">${timed.map(e=>{const conflict=timed.some(o=>o!==e&&o.transparency!=='transparent'&&e.transparency!=='transparent'&&new Date(start(o))<new Date(end(e))&&new Date(end(o))>new Date(start(e)));const cat=/academy|school|basketball/i.test(e.summary)?'school':/dent|doctor/i.test(e.summary)?'personal':/position|meeting|report/i.test(e.summary)?'work':'family';return `<article class="event"><div class="time">${time(start(e))}<small>${range===7?dateOf(e).slice(5):time(end(e))}</small></div><div class="event-body ${cat}"><h3>${privateText(e.summary)}</h3>${tag(t('category.'+cat))}${conflict?tag(t('conflict'),'red'):''}<p>${privateText(e.location||t('noLocation'))}</p>${link(e.htmlLink)}</div></article>`;}).join('')||`<div class="empty">${t('emptyEvents')}</div>`}</div></section><section class="card"><div class="section-head"><h2>${t('todos')}</h2><span class="muted">${t('pendingCount',{n:todos.filter(c=>!c.user.done).length})}</span></div>${todos.slice(0,10).map(todoView).join('')||`<div class="empty">${t('emptyTodos')}</div>`}</section></div>
 <section class="section"><div class="section-head"><h2>${t('contracts')}</h2><button data-go="contracts" class="text-button">${t('details')} →</button></div><div class="projects-grid">${S.contracts.filter(c=>c.actionable||c.needsReview||c.latestBill).slice(0,3).map(contractCard).join('')||`<div class="card empty">${t('contract.empty')}</div>`}</div></section><section class="section"><div class="section-head"><h2>${t('movingProjects')}</h2><button data-go="projects" class="text-button">${t('details')} →</button></div><div class="projects-grid">${S.projects.map(projectCard).join('')||`<div class="card empty">${t('chooseProjects')}</div>`}</div></section><div class="card"><div class="section-head"><h2>${t('attention')}</h2><button data-go="inbox" class="text-button">${t('pendingCount',{n:reviews().length})} →</button></div><div class="state-grid">${S.statuses.map(s=>tag(`${s.source.startsWith('calendar:')?'Google Calendar':s.source} · ${state(s.state)}`,['failed','partial','authorization_required'].includes(s.state)?'amber':'')).join('')}</div><p class="muted">${t('sourceWarning')}</p></div>`;}
function todoView(c){return `<div class="todo ${c.user.done?'done':''}"><input aria-label="${t('complete')}" type="checkbox" data-done="${esc(c.id)}" ${c.user.done?'checked':''}><div class="todo-body"><div class="todo-title">${privateText(localized(c,'title'))}</div><small>${esc(c.due?t('due',{date:c.due}):t('noDue'))} · ${category(c.category)}</small>${c.user.note?`<small>${privateText(c.user.note)}</small>`:''}<div class="todo-tools"><button data-note="${esc(c.id)}">${t('note')}</button><button data-snooze="${esc(c.id)}">${t('snooze')}</button>${link(c.source?.url,t('mail'))}</div></div></div>`;}
function projectCard(p){return `<article class="card project"><div class="project-icon">▦</div><h3>${privateText(p.name)}</h3>${tag(S.settings.privacy?t('hidden'):localized(p,'stage')||t('unknown'))}${p.stale?tag(t('stale'),'amber'):tag(state(p.change||'updated'),p.change==='failed'?'red':'')}<p><strong>${t('recentWork')}</strong><br>${privateText(localized(p,'completed')?.[0]||t('unknown'))}</p><p><strong>${t('nextStep')}</strong><br>${privateText(localized(p,'next')?.[0]||t('unknown'))}</p>${p.blockers?.length?`<p><strong>${t('blockers')}</strong><br>${privateText(localized(p,'blockers').join('; '))}</p>`:''}${p.deadline?`<p>${t('deadline')}: ${privateText(p.deadline)}</p>`:''}<details><summary>${t('sourcesAndTask')}</summary><p>${privateText((p.sources||[]).join('; '))}</p><p>${t('findTask')} ${privateText(p.threadTitle||p.name)}</p><p>${privateText(p.threadId)}</p></details><div class="meta">${t('lastActivity')} ${stamp(p.lastActivity)}<br>${t('lastChecked')} ${stamp(p.checkedAt)}</div></article>`;}
function projectPage(){return `<div class="banner">${t(S.projects.length?'projectIntro':'projectPreview')}</div><button id="refreshProjects" class="primary">↻ ${t('refreshProjects')}</button><div class="projects-grid">${(S.projects.length?S.projects:S.availableProjects).map(projectCard).join('')}</div>${S.projectFiles.map(f=>`<div class="card">${stamp(f.checkedAt)} · ${state(f.state)}</div>`).join('')}`;}
function candidateView(c){return `<article class="card review"><div class="review-head"><h3>${privateText(localized(c,'title'))}</h3>${tag(c.kind==='contract'?t('contracts'):state(c.kind==='todo'?'todo':c.result.status),'amber')}</div><p>${tag(category(c.category))} ${c.kind==='contract'?t('contract.missing'):`${esc(c.start||c.due||t('timeUnknown'))} ${c.end?' → '+esc(c.end):''} · ${esc(c.timezone||t('zoneUnknown'))}`}</p><p>${privateText((localized(c,'ambiguities')||[]).map(x=>messages[x]?t(x):x).join('; '))}</p><details><summary>${t('original')}</summary><blockquote>${privateText(c.evidence||c.result.reason||t('unknown'))}</blockquote></details>${c.preparation?.length?`<p>${t('prepare')}: ${privateText(localized(c,'preparation').join('; '))}</p>`:''}<div class="row">${link(c.source?.url)}${c.kind==='contract'?`<button data-contract-candidate="${esc(c.id)}">${t('confirm')}</button>`:c.kind!=='todo'?`<button data-confirm="${esc(c.id)}">${t('confirm')}</button>`:''}<button data-dismiss="${esc(c.id)}">${t('hide')}</button><button data-note="${esc(c.id)}">${t('note')}</button></div>${c.user.note?`<p>${privateText(c.user.note)}</p>`:''}</article>`;}
function inboxView(){return `<div class="banner">${t('inboxIntro')}</div>${S.candidates.filter(c=>!c.user.dismissed&&!c.bill).map(candidateView).join('')}`;}
function money(n,c){return new Intl.NumberFormat(locale(),{style:'currency',currency:c.currency,maximumFractionDigits:4}).format(n);}
function contractCard(c){if(c.providerKey)return serviceCard(c);return `<article class="card contract"><div class="review-head"><h3>${privateText(c.title)}</h3>${tag(t('contract.'+c.type))}</div><p>${privateText(c.provider)} ${tag(t('contract.'+c.status),c.needsReview?'amber':'')}</p><h2>${c.anchor?t(c.days<0?'contract.overdue':c.days===0?'contract.today':'contract.dueIn',{n:Math.abs(c.days)}):t('contract.missing')}</h2>${c.anchor?`<p>${t('contract.'+c.anchor.kind)} · <strong>${c.anchor.date}</strong>${c.anchor.derived?`<small class="muted"> · ${t('contract.derived')}</small>`:''}</p>`:''}<p>${t('contract.autoRenew')}: ${t('contract.'+(c.autoRenew===true?'yes':c.autoRenew===false?'no':'unknown'))}</p>${c.currentPrice!==null?`<p>${t('contract.currentPrice')}: ${privateText(money(c.currentPrice,c))} · ${t('contract.'+c.priceUnit)}</p>`:''}${c.priceIncrease!==null?`<p class="price-alert">${privateText(t('contract.increase',{amount:money(c.priceIncrease,c),unit:t('contract.'+c.priceUnit)}))}</p>`:`<p class="muted">${t('contract.noPriceGuess')}</p>`}<details><summary>${t('details')}</summary>${c.milestones.map(m=>`<p>${t('contract.'+m.kind)}: ${m.date}</p>`).join('')}${c.paymentDueDate?`<p>${t('contract.paymentDueDate')}: ${c.paymentDueDate}</p>`:''}<p>${privateText(c.notes)}</p>${c.evidence?`<blockquote>${privateText(c.evidence)}</blockquote>`:''}</details><div class="row"><button data-contract-edit="${esc(c.id)}">${t('contract.edit')}</button>${c.reminderId&&c.status==='active'?`<button data-contract-done="${esc(c.id)}">${t(c.user.done?'undo':'contract.markReviewed')}</button><button data-contract-snooze="${esc(c.id)}">${t('snooze')}</button>`:''}${link(c.source?.url)}</div>${c.user.done?`<p class="muted">${t('contract.reviewed')}</p>`:''}${c.user.snooze?`<p class="muted">${t('snooze')}: ${c.user.snooze}</p>`:''}</article>`;}
function contractsView(){return `<div class="banner">${t('bill.intro')} ${t('contract.defaultLeads')}</div><div class="section-head"><p>${t('contract.verifyTerms')}</p><button id="addContract" class="primary">＋ ${t('contract.add')}</button></div><div class="projects-grid">${S.contracts.map(contractCard).join('')||`<div class="card empty">${t('contract.empty')}</div>`}</div><section class="section"><h2>${t('contract.reviewMail')}</h2>${S.candidates.filter(c=>c.kind==='contract'&&!c.user.dismissed).map(candidateView).join('')}</section>`;}
function billState(c){return c.bill.paid?'bill.paid':c.bill.autoPay?(c.bill.dueDate&&c.bill.dueDate<day()?'bill.verify':'bill.scheduled'):'bill.unverified';}
function serviceCard(c){
 const latest=c.latestBill,b=latest?.bill,done=latest?.user.done,p=!b&&c.paymentObservation?.termEnd===c.endDate?c.paymentObservation:null;
 return '<article class="card contract service"><div class="review-head"><h3>'+privateText(c.provider)+'</h3>'+tag(t('contract.'+c.type))+'</div>'+
 '<div class="muted">'+(p?t('bill.termPremium',{n:p.months}):t('bill.latest'))+'</div><h2 class="bill-amount">'+(b?privateText(money(b.amount,b)):p?privateText(money(p.premium,c)):t('bill.unknown'))+'</h2>'+
 (b?'<p class="muted">'+t(b.amountBasis==='balance'?'bill.balance':'bill.variable')+'</p><p>'+esc(t('bill.due',{date:b.dueDate||t('unknown')}))+'</p><p>'+tag(t(billState(latest)),b.paid?'':'amber')+'</p>':'')+
 (p?'<p>'+tag(t('bill.paidInFull'))+'</p><p>'+privateText(t('bill.paidAmount',{amount:money(p.paid,c)}))+'</p><p>'+privateText(t('bill.remaining',{amount:money(p.remaining,c)}))+'</p><p class="muted">'+esc(t('bill.portalEvidence',{date:p.observedAt.slice(0,10)}))+'</p>':'')+
 (b?.conflict?'<p class="price-alert">'+t('bill.conflict')+'</p>':'')+
 (c.billDelta>0?'<p class="price-alert">'+privateText(t('bill.changed',{amount:money(c.billDelta,c)}))+'</p>':'')+
 (c.currentPrice!==null?'<p>'+t(c.priceBasis==='estimate'?'bill.estimated':'contract.currentPrice')+': <strong>'+privateText(money(c.currentPrice,c))+'</strong> · '+t('contract.'+c.priceUnit)+'</p>':'')+
 '<hr><p>'+t('contract.endDate')+': <strong>'+esc(c.endDate||t('bill.endUnknown'))+'</strong></p>'+
 c.milestones.filter(m=>m.kind!=='endDate').map(m=>'<p>'+t('contract.'+m.kind)+': <strong>'+esc(m.date)+'</strong></p>').join('')+
 '<p>'+privateText(localized(c,'notes'))+'</p>'+
 (latest?'<div class="row">'+link(latest.source?.url,t('mail'))+'</div><label class="inline"><input type="checkbox" data-done="'+esc(latest.id)+'" '+(done?'checked':'')+'>'+t('bill.checked')+'</label>':'')+
 (latest?.user.note?'<p>'+privateText(latest.user.note)+'</p>':'')+
 (latest?'<div class="row"><button data-note="'+esc(latest.id)+'">'+t('note')+'</button><button data-snooze="'+esc(latest.id)+'">'+t('snooze')+'</button></div>':'')+
 '<details><summary>'+t('bill.history')+' ('+c.bills.length+')</summary>'+c.bills.map(x=>'<div class="bill-history"><strong>'+privateText(money(x.bill.amount,x.bill))+'</strong> · '+esc(x.bill.dueDate||t('unknown'))+'<p>'+t(billState(x))+'</p>'+x.bill.sources.map(s=>link(s.url,t('mail'))).join(' · ')+'</div>').join('')+'</details>'+
 '<details><summary>'+t('bill.sources')+'</summary><blockquote>'+privateText(c.evidence)+'</blockquote>'+[c.source,...(c.extraSources||[])].filter(Boolean).map(s=>link(s.url,t('source'))).join(' · ')+'</details>'+
 '<div class="row"><button data-contract-edit="'+esc(c.id)+'">'+t('contract.edit')+'</button>'+
 (c.reminderId?'<button data-contract-done="'+esc(c.id)+'">'+t(c.user.done?'undo':'contract.markReviewed')+'</button><button data-contract-snooze="'+esc(c.id)+'">'+t('snooze')+'</button>':'')+'</div></article>';
}
function settingsView(){return `<div class="settings-grid"><section class="card"><h2>${t('preferences')}</h2><label>${t('language')}<select id="language">${[['en-US','English (United States)'],['zh-CN','中文 + English'],['es-US','Español (Estados Unidos)']].map(([value,label])=>`<option value="${value}" ${value===locale()?'selected':''}>${label}</option>`).join('')}</select></label><p>Try the original three-language interface. Sample record text stays in English.</p><h2>${t('tracking')}</h2>${S.availableProjects.map(p=>`<label class="inline"><input type="checkbox" name="project" value="${esc(p.id)}" ${S.settings.projects.includes(p.id)?'checked':''}>${privateText(p.name)}</label>`).join('')}<button id="saveProjects">${t('saveProjects')}</button><p id="saveProjectsStatus" role="status">${esc(saveStatus('saveProjects'))}</p></section><section class="card"><h2>Public demo boundaries</h2><p>The private Windows application has separate local services. This GitHub Pages version contains only interface assets and a synthetic in-memory data adapter.</p><p>No account login, credential import, notifications, email access, calendar writes, or project-file access is enabled here.</p><p>Edits stay in this tab and disappear on reload. No information is uploaded.</p></section></div>`;}
function logsView(){return `<div class="card"><h2>${t('recentLogs')}</h2>${S.logs.map(l=>`<div class="log"><span>${stamp(l.at)}</span><span>${esc(l.action)}</span><span>${tag(l.status,l.status==='failed'?'red':'')}</span><details><summary>${t('technicalDetails')}</summary>${privateText(l.detail)}</details></div>`).join('')}</div>`;}
function eventDialog(c){if(S.settings.privacy)return flash(t('unhideFirst'));$('edit').innerHTML=`<form method="dialog"><h2>${t('confirm')}</h2><p>${esc(localized(c,'title'))}</p>${[['Start','start',c.start],['End','end',c.end],['Zone','originalZone',c.timezone]].map(([id,key,v])=>`<label>${t(key)}<input id="edit${id}" value="${esc(v)}"></label>`).join('')}<label class="inline"><input id="editAllDay" type="checkbox" ${c.allDay?'checked':''}>${t('allDay')}</label><p>${t('confirmTimeHelp')}</p><div class="row"><button value="cancel">${t('back')}</button><button id="confirmItem" class="primary" type="button">${t('confirm')}</button></div></form>`;$('confirmItem').onclick=async()=>{const r=await act('/api/item',{id:c.id,confirmed:true,kind:'event',start:$('editStart').value,end:$('editEnd').value,timezone:$('editZone').value,allDay:$('editAllDay').checked});if(r)$('edit').close();};$('edit').showModal();}
function contractDialog(c={},candidateId){if(S.settings.privacy)return flash(t('unhideFirst'));const select=(key,values,chosen)=>`<label>${t('contract.'+key)}<select id="ct-${key}">${values.map(v=>`<option value="${v}" ${v===chosen?'selected':''}>${messages['contract.'+v]?t('contract.'+v):v}</option>`).join('')}</select></label>`,input=(key,type='text')=>`<label>${t('contract.'+key)}<input id="ct-${key}" type="${type}" ${type==='number'?'min="0" step="any"':''} value="${esc(c[key])}"></label>`;
 $('contractEdit').innerHTML=`<form method="dialog"><h2>${t(c.id?'contract.edit':'contract.add')}</h2><p class="muted">${t('contract.verifyTerms')}</p><div class="contract-form">${input('title')}${input('provider')}${select('type',['insurance','electricity','internet','phone','water','subscription','other'],c.type||'other')}${select('status',['active','review','renewed','cancelled'],c.status||'active')}${['endDate','renewalDate','noticeDeadline','rateChangeDate','promoEndDate','paymentDueDate'].map(k=>input(k,'date')).join('')}${input('noticeDays','number')}${select('autoRenew',['unknown','yes','no'],c.autoRenew===true?'yes':c.autoRenew===false?'no':'unknown')}${input('currentPrice','number')}${input('newPrice','number')}${select('currency',['USD','CAD','EUR','GBP','MXN'],c.currency||'USD')}${select('priceUnit',['month','year','kWh','term'],c.priceUnit||'month')}</div><label>${t('contract.reminderDays')}<input id="ct-reminderDays" value="${esc((c.reminderDays||[60,30,14,7,1,0]).join(', '))}"></label><label>${t('contract.notes')}<textarea id="ct-notes">${esc(c.notes)}</textarea></label>${c.evidence?`<details><summary>${t('original')}</summary><blockquote>${esc(c.evidence)}</blockquote></details>`:''}<div id="contractError" role="alert"></div><div class="row"><button value="cancel">${t('back')}</button><button type="button" class="primary" id="saveContract">${t('save')}</button></div></form>`;
 $('saveContract').onclick=async()=>{const b={id:c.id,candidateId};for(const key of ['title','provider','type','status','endDate','renewalDate','noticeDeadline','rateChangeDate','promoEndDate','paymentDueDate','currency','priceUnit','notes'])b[key]=$('ct-'+key).value;for(const key of ['noticeDays','currentPrice','newPrice'])b[key]=$('ct-'+key).value===''?null:Number($('ct-'+key).value);b.autoRenew=$('ct-autoRenew').value==='unknown'?null:$('ct-autoRenew').value==='yes';b.reminderDays=$('ct-reminderDays').value.split(',').map(x=>x.trim()===''?null:Number(x.trim()));try{await api('/api/contracts',b);$('contractEdit').close();dirty=false;await load();}catch(e){$('contractError').textContent=messages[e.message]?t(e.message):t('operationFailed')+' '+e.message;}};$('contractEdit').showModal();}
function bind(){const all=(selector,handler,event='onclick')=>document.querySelectorAll(selector).forEach(b=>b[event]=()=>handler(b));const on=(id,fn)=>{if($(id))$(id).onclick=fn;},vals=n=>[...document.querySelectorAll(`input[name="${n}"]:checked`)].map(x=>x.value);
 all('[data-go]',b=>{page=b.dataset.go;dirty=false;$('notice').innerHTML='';render();});all('[data-range]',b=>{range=Number(b.dataset.range);render();});all('[data-done]',b=>act('/api/item',{id:b.dataset.done,done:b.checked}),'onchange');all('[data-note]',b=>{if(S.settings.privacy)return flash(t('unhideFirst'));const c=S.candidates.find(c=>c.id===b.dataset.note),note=prompt(t('notePrompt'),c.user.note||'');if(note!==null)act('/api/item',{id:c.id,note});});all('[data-snooze]',b=>{const snooze=prompt(t('snoozePrompt'),shift(day(),1));if(snooze!==null)act('/api/item',{id:b.dataset.snooze,snooze});});all('[data-dismiss]',b=>act('/api/item',{id:b.dataset.dismiss,dismissed:true}));all('[data-confirm]',b=>eventDialog(S.candidates.find(c=>c.id===b.dataset.confirm)));
 on('addContract',()=>contractDialog());all('[data-contract-edit]',b=>contractDialog(S.contracts.find(c=>c.id===b.dataset.contractEdit)));all('[data-contract-candidate]',b=>{const c=S.candidates.find(c=>c.id===b.dataset.contractCandidate);contractDialog({...c.contractDraft,title:localized(c,'title'),evidence:c.evidence},c.id);});all('[data-contract-done]',b=>{const c=S.contracts.find(c=>c.id===b.dataset.contractDone);act('/api/contracts/reminder',{id:c.id,reminderId:c.reminderId,done:!c.user.done});});all('[data-contract-snooze]',b=>{const c=S.contracts.find(c=>c.id===b.dataset.contractSnooze),snooze=prompt(t('snoozePrompt'),shift(day(),1));if(snooze!==null)act('/api/contracts/reminder',{id:c.id,reminderId:c.reminderId,snooze});});
 on('refreshProjects',async()=>{if(await act('/api/projects/refresh',{}))flash('Sample project timestamps refreshed in this tab only.');});on('saveCalendars',()=>{const selectedCalendars=vals('cal');return saveSettingsAction('saveCalendars',{selectedCalendars},'calendarsSaved',{n:selectedCalendars.length});});on('saveProjects',()=>{const projects=vals('project');return saveSettingsAction('saveProjects',{projects},'projectsSaved',{n:projects.length});});
 if($('language'))$('language').onchange=async()=>{if(await act('/api/settings',{locale:$('language').value}))flash(t('languageSaved'));};
 on('privacy',()=>act('/api/settings',{privacy:!S.settings.privacy}));on('sync',()=>flash('This public sample is not connected to any service.'));on('quit',()=>{resetDemo();load();});on('resetDemo',()=>{resetDemo();load();});document.querySelectorAll('#content input,#content textarea,#content select:not(#language)').forEach(e=>e.addEventListener('input',()=>{dirty=true;}));}
try{token=(await api('/api/token')).csrf;await load();const result=new URLSearchParams(location.search).get('oauth');if(result){flash(t(result==='success'&&S.connected?'oauth.success':'oauth.failed'));history.replaceState(null,'','/');}}catch{flash(t('serviceError'));}
setInterval(()=>{if(!dirty&&!oauthBusy&&!savingCount&&!document.querySelector('input:focus,textarea:focus,select:focus,dialog[open]'))load();},15000);
