// Public-only adapter. Deliberately contains no fetch, OAuth, filesystem or notification access.
const copy=x=>structuredClone(x);
const day=()=>new Date().toISOString().slice(0,10);
const shift=(date,n)=>new Date(Date.parse(date+'T12:00:00Z')+n*86400000).toISOString().slice(0,10);
function seed(){const today=day(),now=new Date().toISOString();return {
 settings:{locale:'en-US',timezone:'America/Chicago',privacy:false,notifications:false,selectedCalendars:['sample'],projects:['p1','p2'],familyNames:[],intervalMinutes:15,lookbackDays:30},
 connected:false,syncing:false,account:'sample@example.invalid',oauth:{configured:false},bridge:{generatedAt:now},
 calendars:[{id:'sample',summary:'Sample calendar',accessRole:'reader'}],statuses:[{source:'synthetic-demo',state:'updated'}],projectFiles:[],logs:[{at:now,action:'Loaded synthetic examples',status:'demo',detail:'No private services or files were accessed.'}],
 events:[{id:'e1',calendarId:'sample',summary:'Design review meeting',location:'Sample meeting room',start:{dateTime:today+'T10:00:00-05:00'},end:{dateTime:today+'T11:00:00-05:00'}},{id:'e2',calendarId:'sample',summary:'Community workshop',location:'Fictional community center',start:{dateTime:today+'T16:00:00-05:00'},end:{dateTime:today+'T17:00:00-05:00'}},{id:'e3',calendarId:'sample',summary:'Prepare event materials',location:'Sample workspace',start:{dateTime:shift(today,1)+'T09:00:00-05:00'},end:{dateTime:shift(today,1)+'T09:30:00-05:00'}}],
 candidates:[{id:'t1',kind:'todo',title:'Review the neighborhood newsletter',due:today,category:'工作',user:{},result:{status:'todo'},evidence:'Entirely fictional task for this public demonstration.'},{id:'t2',kind:'todo',title:'Prepare workshop supplies',due:shift(today,1),category:'家庭',user:{},result:{status:'todo'},evidence:'Sample task; no email source.'},{id:'r1',kind:'event',title:'Confirm a sample meeting time',start:shift(today,2)+'T14:00:00',end:shift(today,2)+'T15:00:00',timezone:'America/Chicago',category:'工作',user:{},result:{status:'review'},ambiguities:['Confirm the time with the organizer.'],evidence:'Fictional invitation: shall we meet on Thursday afternoon? No real message was read.'}],
 availableProjects:[{id:'p1',name:'Community newsletter',stage:'Draft review',completed:['Prepared the sample layout'],next:['Review the example articles'],blockers:[],lastActivity:now,checkedAt:now,change:'updated',sources:['Synthetic example'],threadTitle:'Sample project, not a real Codex task'},{id:'p2',name:'Workshop directory',stage:'Content preparation',completed:['Organized example categories'],next:['Check the sample descriptions'],blockers:[],lastActivity:now,checkedAt:now,change:'updated',sources:['Synthetic example']}],
 contracts:[{id:'c1',title:'Sample internet plan',provider:'Example Network',type:'internet',status:'active',endDate:shift(today,30),noticeDeadline:shift(today,7),renewalDate:'',rateChangeDate:'',promoEndDate:'',paymentDueDate:'',noticeDays:null,reminderDays:[60,30,14,7,1,0],autoRenew:true,currentPrice:50,newPrice:60,currency:'USD',priceUnit:'month',notes:'Fictional subscription. No service provider is connected.',user:{}}]
};}
let state=seed();
export function resetDemo(){state=seed();}
function dateValue(v){return /^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v+'T12:00:00Z'))&&new Date(v+'T12:00:00Z').toISOString().slice(0,10)===v;}
function contractView(c){const milestones=['endDate','renewalDate','noticeDeadline','rateChangeDate','promoEndDate'].filter(k=>c[k]).map(kind=>({kind,date:c[kind]})).sort((a,b)=>a.date.localeCompare(b.date));const anchor=milestones[0]||null;const days=anchor?Math.round((Date.parse(anchor.date)-Date.parse(day()))/86400000):null;return {...c,milestones,anchor,days,needsReview:!anchor||c.status==='review',reminderId:anchor?c.id+'-sample':null,actionable:!!anchor&&c.status==='active'&&!c.user.done&&(!c.user.snooze||c.user.snooze<=day()),priceIncrease:c.newPrice!==null&&c.currentPrice!==null&&c.newPrice>c.currentPrice?c.newPrice-c.currentPrice:null};}
export async function demoApi(path,b){
 if(path==='/api/token')return {csrf:'public-demo-no-server'};
 if(path==='/api/state')return copy({...state,projects:state.availableProjects.filter(p=>state.settings.projects.includes(p.id)),contracts:state.contracts.map(contractView)});
 if(path==='/api/settings'){for(const key of ['locale','privacy','projects','selectedCalendars'])if(key in b){if(key==='locale'&&!['en-US','zh-CN','es-US'].includes(b[key]))throw Error('Unsupported language');state.settings[key]=copy(b[key]);}return {ok:true};}
 if(path==='/api/item'){const item=state.candidates.find(c=>c.id===b.id);if(!item)throw Error('Sample item not found');for(const key of ['done','dismissed','note','snooze'])if(key in b)item.user[key]=copy(b[key]);if(b.confirmed){item.result={status:'existing'};item.user.note='Reviewed in this tab only. No calendar event created.';}return {ok:true};}
 if(path==='/api/contracts'){if(!String(b.title||'').trim())throw Error('contract.titleRequired');for(const k of ['endDate','renewalDate','noticeDeadline','rateChangeDate','promoEndDate','paymentDueDate'])if(b[k]&&!dateValue(b[k]))throw Error('contract.invalidDate');for(const k of ['currentPrice','newPrice'])if(b[k]!==null&&(!Number.isFinite(b[k])||b[k]<0))throw Error('contract.invalidPrice');const old=state.contracts.find(c=>c.id===b.id);const c={...copy(b),id:old?.id||'sample-'+crypto.randomUUID(),user:old?.user||{}};if(old)state.contracts=state.contracts.map(x=>x.id===old.id?c:x);else state.contracts.push(c);return {ok:true};}
 if(path==='/api/contracts/reminder'){const c=state.contracts.find(x=>x.id===b.id);if(!c)throw Error('Sample record not found');if('done'in b)c.user.done=b.done;if('snooze'in b)c.user.snooze=b.snooze;return {ok:true};}
 if(path==='/api/projects/refresh'){for(const p of state.availableProjects)p.checkedAt=new Date().toISOString();return {ok:true};}
 throw Error('Unavailable in the public demonstration. No service was contacted.');
}
